name: Setup Environment
description: 'Setup environment'

runs:
  using: "composite"
  steps:
    - name: Install JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Install flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'

    - name: Install project dependencies
      shell: bash
      run: flutter pub get
