name: Run Test Flow

on:
  push:
    branches: [ 'main' ]

permissions:
  actions: write
  contents: write

env:
  APK_NAME: "DazzleMe-Staging.apk"
  IPA_NAME: "DazzleMe-Staging.ipa"
  APP_NAME: "DazzleMe App - Staging"
  FIREBASE_DISTRIBUTION_LINK: "https://appdistribution.firebase.google.com/testerapps/"

jobs:
  deploy-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      android-version: ${{ steps.android-version.outputs.VERSION_NAME }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Define Long JSON Text and Assign to ENV
        uses: actions/github-script@v7
        with:
          script: |
            const variables = '{"cardsV2":[{"cardId":"API Automation","card":{"header":{"title":"Wheelhouse App - Staging","subtitle":"API Automation Workflow Report","imageUrl":"https://wheelhouse.site/assets/front/images/logo.png"},"sections":[{"widgets":[{"textParagraph":{"text":"<font color=\"#C62828\"><b>API failure detected. Please check report for more details. 🚨🚨🚨</b></font>"}},{"buttonList":{"buttons":[{"text":"View Report","color":{"red":0.25,"green":0.42,"blue":0,"alpha":1},"onClick":{"openLink":{"url":"https://developers.google.com/chat/ui/widgets/button-list"}}}]}}]}]}}]}'
            
            const { request } = require("@octokit/request");
            const response = await request('POST ${{ secrets.GOOGLE_CHAT_WEBHOOK }}', {
              headers: {
                'content-type': 'application/json'
              },
              data: {
                title: 'foo',
                body: 'bar',
                userId: 1
              }
            });

            console.log(response.data);

      - name: Notify release on google chat
        shell: bash
        run: |
          curl --location '${{ secrets.GOOGLE_CHAT_WEBHOOK }}' --header 'Content-Type: application/json' --data '${{ env.LONG_TEXT }}'
